### ISSUE TITLE
missing /usr/lib/os-session-select ?

### ISSUE THREAD

**Issue by zany130** [ChimeraOS/gamescope-session-steam#13]
https://github.com/ChimeraOS/gamescope-session-steam/blob/015e09825d4f9a2dfdbc20fc2711e2dcee2af68a/usr/bin/steamos-session-select#L4 calls `/usr/lib/os-session-select/` but this is not included in either this repo or  https://github.com/ChimeraOS/gamescope-session and is not installed by the aur packages.

looking at nobara implementation,
Isn't this what allows one to quick-reboot into either their DE or the gamescope session?

**Comment by alkazar** [comment]
That file cannot be included in the package because it is highly dependent on the distro and specific setup, DE, etc.

**Comment by zany130** [comment]
nobara os-session-select works on different de's. I got the chimeraos gamescope session working like the steam decks (able to switch from desktop mode to gamescope session and vice versa) here https://forum.garudalinux.org/t/gamescope-steam-session/37887

**Comment by alkazar** [comment]
You would still need to configure autologin. It doesn't make sense to have this in a general purpose OS.
